apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ShikhaVashishtha
  annotations:
    github.com/project-slug: ShikhaVashishtha/software_template
spec:
  type: other
  lifecycle: unknown
  owner: guests
